name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
#     if: ${{ contains(github.event.head_commit.message, 'run_ci') }}
    strategy:
      matrix:
        version:
          - '1.7' # LTS
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        arch:
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: Install Julia dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          # dev mono repo versions
          pkg"dev . ./MakieCore ./GLMakie ./ReferenceTests"
      - name: Run the tests
        id: referencetests
        continue-on-error: true
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project=monorepo -e 'using Pkg; Pkg.test("GLMakie", coverage=true)'
          && echo "TESTS_SUCCESSFUL=true" >> $GITHUB_ENV
      - name: Comment if there are missing refimages
        if: matrix.version == '1' && steps.referencetests.outputs.n_missing_refimages != '0'
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ## Missing reference images
            Found ${{steps.referencetests.outputs.n_missing_refimages}} new images without existing references.
            Upload new reference images before merging this PR.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
      - name: Upload test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ReferenceImages_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.version }}
          path: |
            ./GLMakie/test/recorded_reference_images/
      - name: Fail after artifacts if tests failed
        if: ${{ env.TESTS_SUCCESSFUL != 'true' }}
        run: exit 1
#       - uses: julia-actions/julia-processcoverage@v1
#       - uses: codecov/codecov-action@v1
#         with:
#           file: lcov.info
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
